/* SORT THE CUSTOMERS FROM LOWEST TO HIGHEST SCORES WITH NULLS APPEARING LAST
*/
SELECT 
CustomerID,
Score
FROM Sales.Customers
ORDER BY CASE WHEN Score IS NULL THEN 1 ELSE 0 END, Score 

--FIND THE SALES PRICE FOR EACH ORDER BY DIVIDING SALES BY QUANTITY --

SELECT 
OrderID,
Sales,
Quantity,
Sales / NULLIF (Quantity, 0) AS Price 
FROM Sales.Orders

--IDENTIFY THE CUSTOMERS WHO HAVE NO SCORES--

SELECT *
FROM Sales.Customers
WHERE Score IS NULL

--SHOW A LIST OF CUSTOMERS WHO HAVE SCORES--

SELECT *
FROM Sales.Customers
WHERE Score IS NOT NULL

--LIST ALL DETAILS OF CUSTOMERS WHO HAVE NOT PLACED ANY ORDERS--

SELECT c.*,
o.OrderID
FROM Sales.Customers AS c 
LEFT JOIN Sales.Orders AS o 
ON c.CustomerID = o.CustomerID
WHERE o.CustomerID IS NULL 

WITH Orders AS (
    SELECT 1 Id, 'A' Category UNION
    SELECT 2, NULL UNION
    SELECT 3, '' UNION
    SELECT 4, '  '
)
SELECT 
*,
DATALENGTH(Category) AS CategoryLength,
DATALENGTH(TRIM(Category)) AS TRIMMED_CAT,
NULLIF(TRIM(Category), '') AS POL2,
COALESCE(NULLIF(TRIM(Category), ''), 'Unknown') AS POL3 
FROM Orders  