/* RETRIEVE ALL CUSTOMERS WHOSE SCORE FALLS IN THE RANGE BETWEEN 100 AND 500 */

SELECT *
FROM customers

SELECT *
FROM customers
WHERE score BETWEEN 100 AND 500 

SELECT *
FROM customers
WHERE score >= 100
AND score <= 500