/* FIND THE HIGHEST & LOWEST SALES ACROSS ALL ORDERS AND THE HIGHEST & LOWEST
SALES FOR EACH PRODUCT. ADDITIONALLY PROVIDE DETAILS SUCH AS ORDER ID & ORDER 
DATE */

USE SalesDB


SELECT
    OrderID,
    OrderDate,
    Sales,
    ProductID,
    MAX(Sales) OVER() AS MaxSales,
    MIN(Sales) OVER() AS MinSales,
    MAX(Sales) OVER(PARTITION BY ProductID) AS MaxSales_Product,
    MIN(Sales) OVER(PARTITION BY ProductID) AS MinSales_Product  
FROM Sales.Orders

--SHOW THE EMPLOYEES WHO HAVE THE HIGHEST SALARIES

SELECT
*
FROM (
SELECT
*,
MAX(Salary) OVER() AS Max_Salary
FROM Sales.Employees
)t 
WHERE Salary = Max_Salary

--FIND THE DEVIATION OF EACH SALES FROM THE MINIMUM & MAXIMUM SALES AMOUNTS

SELECT
    OrderID,
    OrderDate,
    Sales,
    ProductID,
    MAX(Sales) OVER() AS MaxSales,
    MIN(Sales) OVER() AS MinSales,
    Sales - MIN(Sales) OVER() AS DeviationFromMin,
    MAX(Sales) OVER() - Sales AS DeviationFromMax
FROM Sales.Orders

--CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME

SELECT
    OrderID,
    OrderDate,
    ProductID,
    Sales,
AVG(Sales) OVER(PARTITION BY ProductID) AS AVG_SALES_PRODUCT,
AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate) AS MOVING_AVE_PRODUCT
FROM Sales.Orders

--CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME, INCLUDING
--ONLY THE NEXT ORDER

SELECT
    OrderID,
    OrderDate,
    ProductID,
    Sales,
AVG(Sales) OVER(PARTITION BY ProductID) AS AVG_SALES_PRODUCT,
AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate) AS MOVING_AVE_PRODUCT,
AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate ROWS BETWEEN CURRENT 
ROW AND 1 FOLLOWING) AS MOVING_AVE_PRODUCT_TIME
FROM Sales.Orders

--RANK THE ORDERS BASED ON THEIR SALES FROM HIGHEST TO LOWEST

SELECT
    OrderID,
    ProductID,
    Sales,
    ROW_NUMBER() OVER(ORDER BY Sales DESC) AS UNIQUERANK 
FROM Sales.Orders

--RANK THE ORDERS BASED ON THEIR SALES FROM HIGHEST TO LOWEST

SELECT
    OrderID,
    ProductID,
    Sales,
    ROW_NUMBER() OVER(ORDER BY Sales DESC) AS SALESRANK_ROWNUM,
    RANK() OVER(ORDER BY Sales DESC) AS SALESRANK_RANK,
    DENSE_RANK() OVER(ORDER BY Sales DESC) AS SALES_RANK_DENSERANK 
FROM Sales.Orders

--FIND THE TOP HIGHEST SALES FOR EACH PRODUCT

SELECT
*
FROM(
SELECT
OrderID,
ProductID,
Sales,
MAX(Sales) OVER(PARTITION BY ProductID) HighestSales_Product,
ROW_NUMBER() OVER(PARTITION BY ProductID ORDER BY Sales DESC) RankByProduct
FROM Sales.Orders
)t 
WHERE RankByProduct = 1

--FIND THE LOWEST 2 CUSTOMERS BASED ON THEIR TOTAL SALES

SELECT
*
FROM(
SELECT
CustomerID,
SUM(Sales) AS TotalSales,
ROW_NUMBER() OVER(ORDER BY SUM(Sales)) AS RANKCUSTOMERS
FROM Sales.Orders
GROUP BY
CustomerID
)t 
WHERE RANKCUSTOMERS <= 2

--ASSIGN UNIQUE IDS TO THE ROWS OF THE 'ORDERS ARCHIVE' TABLE

SELECT
ROW_NUMBER() OVER(ORDER BY OrderID, OrderDate) AS UniqueID,
*
FROM Sales.OrdersArchive

/* IDENTIFY DUPLICATE ROWS IN THE TABLE 'ORDERS ARCHIVE' AND RETURN A CLEAN 
RESULT WITHOUT ANY DUPLICATES */

SELECT
*
FROM(
SELECT
ROW_NUMBER() OVER(PARTITION BY OrderID ORDER BY CreationTime DESC) AS RANK,
*
FROM Sales.OrdersArchive
)t 
WHERE
RANK = 1

SELECT
*
FROM(
SELECT
ROW_NUMBER() OVER(PARTITION BY OrderID ORDER BY CreationTime DESC) AS RANK,
*
FROM Sales.OrdersArchive
)t 
WHERE
RANK > 1