USE SalesDB

SELECT
OrderID,
Sales,
NTILE(1) OVER(ORDER BY Sales DESC) AS ONE_BUCKET,
NTILE(2) OVER(ORDER BY Sales DESC) AS TWO_BUCKET,
NTILE(3) OVER(ORDER BY Sales DESC) AS THREE_BUCKET,
NTILE(4) OVER(ORDER BY Sales DESC) AS FOUR_BUCKET
FROM Sales.Orders

--SEGMENT ALL ORDERS INTO 3 CATEGORIES: HIGH, MEDIUM & LOW SALES

SELECT
*,
    CASE WHEN Buckets = 1 THEN 'High'
    WHEN Buckets = 2 THEN 'Medium'
    WHEN Buckets = 3 THEN 'Low'
    END AS SalesSegmentation
FROM(
SELECT
    OrderID,
    Sales,
    NTILE(3) OVER(ORDER BY Sales DESC) AS Buckets
FROM Sales.Orders
)t 

--IN ORDER TO EXPORT THE DATA, DIVIDE THE TABLE INTO TWO GROUPS

SELECT
*,
NTILE(4) OVER(ORDER BY OrderID) AS SEGMENTATION
FROM Sales.Orders

--FIND THE PRODUCTS THAT FALL WITHIN THE HIGHEST 40% OF PRICES

SELECT
*,
CONCAT(CUMULATIVE_DIST *100, '%') AS PERCENTAGE 
FROM(
    SELECT
        Product,
        Price,
        CUME_DIST() OVER(ORDER BY Price DESC) AS CUMULATIVE_DIST 
    FROM Sales.Products
)t 
WHERE CUMULATIVE_DIST <= .4

SELECT
*,
CONCAT(PERCENT_RANK *100, '%') AS PERCENTAGE 
FROM(
    SELECT
        Product,
        Price,
        PERCENT_RANK() OVER(ORDER BY Price DESC) AS PERCENT_RANK  
    FROM Sales.Products
)t 
WHERE PERCENT_RANK <= .4

/* ANALYZE THE MONTH-OVER-MONTH (MoM) PERFORMANCE BY FINDING THE PERCENTAGE CHANGE
IN SALES BETWEEN THE CURRENT AND PREVIOUS MONTH
*/

SELECT
*,
CURRENTMONTH_SALES - PreviousMonthSales AS CHANGE,
ROUND(CAST((CURRENTMONTH_SALES - PreviousMonthSales) AS FLOAT)/(PreviousMonthSales) * 100, 1) 
AS PERCENTAGE_CHANGE
FROM(
SELECT
MONTH(OrderDate) AS ORDER_MONTH,
SUM(Sales) AS CURRENTMONTH_SALES,
LAG(SUM(Sales), 1) OVER(ORDER BY MONTH(OrderDate)) AS PreviousMonthSales
FROM Sales.Orders
GROUP BY MONTH(OrderDate)
)t 

--ANALYZE CUSTOMER LOYALTY BY RANKING CUSTOMERS BASED ON THE AVERAGE NUMBER OF DAYS
--BETWEEN ORDERS

SELECT
CustomerID,
AVG(DaysUntilNextOrder) AVGDAYS,
RANK() OVER(ORDER BY COALESCE(AVG(DaysUntilNextOrder), 9999999)) AS RANKAVG
FROM(
SELECT
OrderID,
OrderDate AS CurrentOrder,
CustomerID,
LEAD(OrderDate) OVER(PARTITION BY CustomerID ORDER BY OrderDate) AS NextOrder,
DATEDIFF(DAY, OrderDate, LEAD(OrderDate) OVER(PARTITION BY CustomerID 
ORDER BY OrderDate)) AS DaysUntilNextOrder
FROM Sales.Orders
)t 
GROUP BY CustomerID