/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE HIGHEST SCORE FIRST
*/
SELECT *
FROM customers
SELECT *
FROM customers
ORDER BY score DESC
/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE LOWEST SCORE FIRST */
SELECT *
FROM customers
ORDER BY score 
SELECT *
FROM customers
ORDER BY country ASC,
score DESC
