--RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN 500

SELECT *
FROM customers

SELECT *
FROM customers
WHERE score > 500

--RETRIEVE ALL CUSTOMERS WITH A SCORE OF 500 OR MORE

SELECT *
FROM customers
WHERE score >= 500

--RETRIEVE ALL CUSTOMERS WITH A SCORE OF LESS THAN 500

SELECT *
FROM customers

SELECT *
FROM customers
WHERE score < 500

--RETRIEVE ALL CUSTOMERS WITH A SCORE OF 500 OR LESS

SELECT *
FROM customers

SELECT *
FROM customers
WHERE score <= 500

--RETRIEVE ALL CUSTOMERS WHO ARE FROM USA AND HAVE A SCORE GREATER THAN 500

SELECT *
FROM customers

SELECT * 
FROM customers
WHERE country = 'USA'
AND score > 500

/* RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM USA OR HAVE A SCORE GREATER THAN 500
*/

SELECT *
FROM customers
WHERE country = 'USA' OR score > 500

--RETRIEVE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500

SELECT *
FROM customers

SELECT *
FROM customers
WHERE NOT score < 500