/*

--STEP 1: FIND THE TOTAL SALES PER CUSTOMER

USE SalesDB;

WITH CTE_TotalSalesCust AS 
    (
    SELECT
    CustomerID,
    SUM(Sales) AS TotalSalesCust
    FROM Sales.Orders
    GROUP BY CustomerID
    )

--STEP 2: FIND THE LAST ORDER DATE FOR EACH CUSTOMER

, CTE_LASTORDERDATE_CUST AS 

(
    SELECT
    CustomerID,
    MAX(OrderDate) AS LASTORDERDATE_CUST
    FROM Sales.Orders
    GROUP BY CustomerID
)

--STEP 3: RANK CUSTOMERS BASED ON TOTAL SALES PER CUSTOMER (NESTED CTE)

, CTE_RANK_CUST AS  
(
SELECT  
    CustomerID,
    TotalSalesCust,
    RANK() OVER(ORDER BY TotalSalesCust DESC) AS RANK_CUST  
FROM CTE_TotalSalesCust
)

--SELECT * FROM CTE_RANK_CUST

--STEP 4: SEGMENT CUSTOMERS BASED ON THEIR TOTAL SALES (NESTED CTE)

, CTE_CUSTOMER_SEGMENT AS 
(SELECT
    CustomerID,
    TotalSalesCust,
    CASE WHEN TotalSalesCust > 100 THEN 'HIGH'
    WHEN TotalSalesCust > 80 THEN 'MEDIUM' 
    ELSE 'LOW'
    END CUSTOMER_SEGMENT 
    FROM CTE_TotalSalesCust

)

--SELECT * FROM CTE_CUSTOMER_SEGMENT

--MAIN QUERY

SELECT
c.CustomerID,
c.FirstName,
c.LastName,
CTS.TotalSalesCust,
LAST.LASTORDERDATE_CUST,
CRC.RANK_CUST,
CCS.CUSTOMER_SEGMENT  
FROM Sales.Customers c 
LEFT JOIN CTE_TotalSalesCust AS CTS 
ON CTS.CustomerID = c.CustomerID
LEFT JOIN CTE_LASTORDERDATE_CUST AS LAST 
ON LAST.CustomerID = c.CustomerID
LEFT JOIN CTE_RANK_CUST AS CRC 
ON CRC.CustomerID = c.CustomerID
LEFT JOIN CTE_CUSTOMER_SEGMENT AS CCS 
ON CCS.CustomerID = c.CustomerID
ORDER BY CustomerID

*/
--GENERATE A SEQUENCE OF NUMBERS FROM 1 TO 20

WITH CTE_SERIES AS 

--ANCHOR QUERY
(
SELECT
1 AS MY_NUMBER
UNION ALL 
--RECURSIVE QUERY

SELECT
MY_NUMBER + 1
FROM CTE_SERIES
WHERE MY_NUMBER < 1000
)

--MAIN QUERY

SELECT *
FROM CTE_SERIES 
OPTION (MAXRECURSION 5000)







