/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE COUNTRY AND THEN BY THE HIGHEST SCORE */
SELECT *
FROM customers
ORDER BY country,
score DESC 
SELECT *
FROM customers
ORDER BY score DESC,
country
