--FIND ALL CUSTOMER WHOSE FIRST NAME STARTS WITH 'M'

SELECT *
FROM customers

SELECT *
FROM customers
WHERE first_name LIKE 'M%'

--FIND ALL CUSTOMERS WHOSE FIRST NAME ENDS WITH 'N'

SELECT *
FROM customers
WHERE first_name LIKE '%n'

/* FIND ALL CUSTOMERS WHOSE FIRST NAME CONTAINS 'r' */

SELECT *
FROM customers
WHERE first_name LIKE '%r%'

--FIND ALL CUSTOMERS WHOSE FIRST NAME HAS 'r' IN THE THIRD POSTITION

SELECT *
FROM customers

SELECT *
FROM customers
WHERE first_name LIKE '__r%'