SELECT
OrderID,
OrderDate,
DATEADD(YEAR, 2, OrderDate) AS TWOYEARSLATER,
DATEADD(MONTH, 3, OrderDate) AS THREEMNTHSLATER,
DATEADD(DAY, -10, OrderDate) AS TENDAYSEARLIER
FROM Sales.Orders

--CALCULATE THE AGE OF EMPLOYEES

SELECT
*
FROM Sales.Employees

SELECT
EmployeeID,
BirthDate,
DATEDIFF(YEAR, BirthDate, GETDATE()) AS AGE
FROM Sales.Employees    

--FIND THE AVERAGE SHIPPING DURATION IN DAYS FOR EACH MONTH

SELECT
*
FROM Sales.Orders

SELECT
MONTH(OrderDate) AS OrderDate,
AVG(DATEDIFF(DAY, OrderDate, ShipDate)) AS AVGDURATION 
FROM Sales.Orders
GROUP BY MONTH(OrderDate)

--FIND THE NUMBER OF DAYS BETWEEN EACH ORDER AND PREVIOUS ORDER

SELECT
OrderID,
OrderDate AS CURRORDERDT,
LAG(OrderDate) OVER (ORDER BY OrderDate) AS PreviousOrderDt,
DATEDIFF(DAY, LAG(OrderDate) OVER (ORDER BY OrderDate), OrderDate) AS DIFFNOOFDAYS
FROM Sales.Orders

SELECT
ISDATE('123') AS DATECHECK,
ISDATE('2025-08-20') AS DATECHECK2,
ISDATE('20-08-2025') AS DATECHECK3,
ISDATE('2025') AS DATECHECK4,
ISDATE('08') AS DATECHECK5

SELECT
--CAST(OrderDate AS DATE) ORDERDATE,
OrderDate,
ISDATE(OrderDate),
CASE WHEN ISDATE(OrderDate) = 1 THEN CAST(OrderDate AS DATE)
ELSE '9999-01-01'  
END NewOrderDt 
FROM
(
    SELECT '2025-08-20' AS ORDERDATE UNION
    SELECT '2025-08-21' UNION
    SELECT '2025-08-23' UNION
    SELECT '2025-08'
)t 
WHERE ISDATE(OrderDate) = 0

--FIND THE AVERAGE SCORE OF THE CUSTOMERS

SELECT
CustomerID,
Score,
COALESCE(Score, 0) AS Score2, 
AVG(Score) OVER() AVGSCORES,
AVG(COALESCE(Score, 0)) OVER() AVGSCORES2
FROM Sales.Customers

/* DISPLAY THE FULL NAME OF CUSTOMERS IN A SINGLE FIELD BY MERGING THEIR FIRST
AND LAST NAMES, AND ADD 10 BONUS POINTS TO EACH CUSTOMER'S SCORE */

SELECT
CustomerID,
FirstName,
LastName,
FirstName + ' ' + COALESCE(LastName, 'N/A') AS FULLNAME,
Score,
COALESCE(Score, 0) AS COALESCESCORE,
COALESCE(Score, 0) + 10 AS SCOREWITHBONUS
FROM Sales.Customers